#!/usr/bin/env bash
# Provision the EditApart preset toolchain for a public install.
#
# Creates a Python venv, installs scenedetect (+ numpy<2 to avoid the opencv
# "KeyError: rad2deg" import crash), and writes a machine-local `env.sh`
# (gitignored) for you to source. This is the setup entrypoint for anyone
# cloning this preset to a fresh machine who does NOT already have scenedetect
# on PATH. If you already have the tools, copy `env.sh.example` to `env.sh`
# instead.
#
# Usage:  bash setup.sh
# After:  source ./env.sh   (then start a DSH session on this preset)
set -euo pipefail

VENV_DIR="${DSH_EDIT_VENV:-$HOME/dsh-edit-venv}"
PY="${DSH_EDIT_PY_SOURCE:-python3}"

echo "==> Creating venv at $VENV_DIR"
"$PY" -m venv "$VENV_DIR"

echo "==> Installing requirements (scenedetect + numpy<2)"
"$VENV_DIR/bin/python" -m pip install --upgrade pip >/dev/null
"$VENV_DIR/bin/pip" install -r "$(dirname "$0")/requirements.txt"

echo "==> Verifying scenedetect imports"
"$VENV_DIR/bin/python" -c "import scenedetect; print('scenedetect', scenedetect.__version__)"

# Rewrite env.sh with the concrete venv path so `source env.sh` just works.
ENV_FILE="$(dirname "$0")/env.sh"
echo "==> Writing $ENV_FILE with DSH_EDIT_VENV=$VENV_DIR"
cat > "$ENV_FILE" <<EOF
# Auto-generated by setup.sh on $(date). Edit paths below if you relocated tools.
export DSH_EDIT_PY="${DSH_EDIT_PY:-$VENV_DIR/bin/python}"
export DSH_SCENEDETECT="${DSH_SCENEDETECT:-$VENV_DIR/bin/scenedetect}"
# export DSH_FFMPEG="${DSH_FFMPEG:-ffmpeg}"
# export DSH_FFPROBE="${DSH_FFPROBE:-ffprobe}"
# export DSH_IMAGEMAGICK="${DSH_IMAGEMAGICK:-/usr/bin/magick}"
echo "DSH_EDIT_PY=$DSH_EDIT_PY"
echo "DSH_SCENEDETECT=$DSH_SCENEDETECT"
EOF

echo
echo "Done. Next: source ./env.sh  (or export those vars), then start a DSH"
echo "session on the ai-video-editor preset."
